# Site settings
title: Zinzoline
description: "La passion est le sexe de l'âme"
baseurl: ""
url: "http://zinzoline.github.io"

twitter: mllezinzoline

timezone: Europe/Paris

markdown: kramdown
paginate: 5

permalink: /:title/

# Assets
sass:
  sass_dir: _sass
#  style: :compressed

# Files to exclude
exclude:
  - README.md
  - bundle
  - CNAME
  - Gemfile
  - Gemfile.lock
  - script
  - assets/css/main.scss
