# Site settings
title: Zinzoline
description: "La passion est le sexe de l'âme"
baseurl: ""
url: "http://zinzoline.github.io"

twitter: mllezinzoline

timezone: Europe/Paris

markdown: kramdown
excerpt_separator: "\n"
paginate: 5

permalink: /:title/

# Assets
sass:
  sass_dir: _sass
  style: :compressed

# Files to exclude
exclude:
  - README.md
  - bundle
  - CNAME
  - Gemfile
  - Gemfile.lock
  - script

# Prose config, see https://github.com/prose/prose/wiki/Prose-Configuration
prose:
  siteurl: "http://zinzoline.github.io"
  media: "assets/img"
  relativeLinks: http://zinzoline.github.io/links.jsonp
  metadata:
    _posts:
      - name: image
        field:
          element: text
          label: Image
          value: ""
      - name: categories
        field:
          label: Categories
          element: select
          placeholder: Select a category
          options:
            - name: Daily Planet
              value: daily-planet
            - name: Pink a boo
              value: pink-a-boo
            - name: Encore du travail ?
              value: travail-travail
            - name: Méninges
              value: meninges
            - name: Mi Fa
              value: mi-fa
            - name: Girls
              value: girls
            - name: Moodlight
              value: moodlight
            - name: Corpore sano
              value: corpore-sano
      - name: layout
        field:
          element: hidden
          value: post
      - name: title
        field:
          element: text
          label: Title
          value: ""
      - name: excerpt
        field:
          element: textarea
          label: Excerpt
          value: ""
          remove_if_blank: true
      - name: author
        field:
          element: text
          label: Author
          value: Zinzoline
      - name: comments_enabled
        field:
          element: checkbox
          label: Comments Enabled
          value: true
      - name: tags
        field:
          element: text
          label: Tags
          value: ""
