#!/bin/sh
# Usage: script/bootstrap
# Ensures all gems are installed locally.
set -e

echo "Please ensure the following dependencies are installed:"
echo "  - bundle"

CMDS="bundle"

for i in $CMDS
do
  command -v $i >/dev/null && continue || { echo "I require $i but it's not installed.  Aborting."; exit 1; }
done

bundle install

echo "\nRun './script/server' and point your browser to http://localhost:4001 to get started !\n"
